### ISSUE TITLE
Tech tree

### ISSUE THREAD

**Issue by simon300500** [MEEPofFaith/Ohno-Missiles-Mod#16]
Ballistic modification plant isn't in tech tree

**Comment by MEEPofFaith** [comment]
well that's a slight issue ain't it

**Comment by MEEPofFaith** [comment]
I attempted to fix it, but I'm waiting on a (helpful) response in #scripting in the discord.
Because I'm not sure how to do the research thing in a script.

**Comment by simon300500** [comment]
Yeah, it's not that big problem, and you made a lot of amazing things so I'm sure nobody will mind waiting for it.👍

**Comment by MEEPofFaith** [comment]
I made an attempt to fix a long time ago, dunno if it worked.
Also dunno why I never closed this, so I guess I'll close it now.
