### ISSUE TITLE
Problem while loading the mod

### ISSUE THREAD

**Issue by IFOZVORTEX** [MEEPofFaith/Ohno-Missiles-Mod#19]
When i try to load the game with the mod on PC version windows 32bits it says this and I don't know how to fix it I searched and found nothing.

What should I do?
![20201127_185723](https://user-images.githubusercontent.com/60710198/100477512-d17b5980-30e8-11eb-990b-02a96fd55b7b.jpg)

**Comment by MEEPofFaith** [comment]
idk eithor and I'm not updating to v6
