### ISSUE TITLE
MEEPofFaith will not be updating to V6

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/Ohno-Missiles-Mod#20]
do not submit issues  about updating, hes not gonna do it

**Comment by USMP-lancer** [comment]
although it might be compatible, and im gonna test a thing

**Comment by USMP-lancer** [comment]
i gave it the minimum game version, and going to test if it actually works, it probably wont but you never know

**Comment by USMP-lancer** [comment]
yea i see few errors, the only ones are redacted unit error, and research error with napalm mixer, there is likely more problems but the thing might work mostly

**Comment by USMP-lancer** [comment]
the turrets need a rework, ammo parameters changed

**Comment by USMP-lancer** [comment]
im gonna learn a bit of hjson so i can port this monster

**Comment by USMP-lancer** [comment]
if i succeed, ill pr the changes, i would reccomend looking over them

**Comment by USMP-lancer** [comment]
yea looks like most of the issues is he changed parameter names

**Comment by USMP-lancer** [comment]
im unsure how the multi lib works so ill probably get the help of the creator to port it

**Comment by USMP-lancer** [comment]
yea its mostly functional, the missile are turning slow, so that might be a problem

**Comment by USMP-lancer** [comment]
yea i think homing power was modified, bumping it up 10x

**Comment by USMP-lancer** [comment]
ok now i am done with turreets, now to check what the fuck happend to the ammo thing

**Comment by USMP-lancer** [comment]
i know too little about the multi lib to port is properly, so ill leave it for now, but all the turrets should be good now

**Comment by USMP-lancer** [comment]
![image](https://user-images.githubusercontent.com/42185819/113317400-f53bef80-92d4-11eb-85b9-938b98ff589b.png)
this is preventing it from loading, i think lightning was changed to something else

**Comment by USMP-lancer** [comment]
that seems to be the only issue

**Comment by USMP-lancer** [comment]
the other two is its simple unable to see air mine, which is probably the lightning issue

**Comment by USMP-lancer** [comment]
ok its working now

**Comment by USMP-lancer** [comment]
yea they seem to work fine, but some sprites are broken, might have fucked a few lines

**Comment by MEEPofFaith** [comment]
I added missiles into Progressed Materials for a reason...

**Comment by USMP-lancer** [comment]
true
